name: sqlmap-lab

services:
  target:
    build:
      context: .
      dockerfile: target.Dockerfile
    ports:
      - "127.0.0.1:18093:8080"
    networks:
      sqlmap_net:
        ipv4_address: 172.47.170.20

  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /work
    volumes:
      - ./outputs:/work/outputs
    depends_on:
      - target
    networks:
      sqlmap_net:
        ipv4_address: 172.47.170.10

networks:
  sqlmap_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.47.170.0/24
