name: gobuster-lab

services:
  target:
    build:
      context: .
      dockerfile: target.Dockerfile
    ports:
      - "127.0.0.1:18089:8080"
      - "127.0.0.1:15354:53/udp"
    networks:
      gobuster_net:
        ipv4_address: 172.43.130.20

  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /work
    volumes:
      - ./outputs:/work/outputs
      - ./wordlists:/work/wordlists:ro
    depends_on:
      - target
    extra_hosts:
      - "gobuster.lab:172.43.130.20"
    networks:
      gobuster_net:
        ipv4_address: 172.43.130.10

networks:
  gobuster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.43.130.0/24
