[libdefaults]
    default_realm = PACKETLAB.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    forwardable = true

[realms]
    PACKETLAB.LOCAL = {
        kdc = 172.66.88.20
        admin_server = 172.66.88.20
    }

[domain_realm]
    .packetlab.local = PACKETLAB.LOCAL
    packetlab.local = PACKETLAB.LOCAL
