name: ffuf-lab

services:
  target:
    build:
      context: .
      dockerfile: target.Dockerfile
    ports:
      - "127.0.0.1:18088:8080"
    networks:
      ffuf_net:
        ipv4_address: 172.42.120.20

  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /work
    volumes:
      - ./outputs:/work/outputs
      - ./wordlists:/work/wordlists:ro
    depends_on:
      - target
    networks:
      ffuf_net:
        ipv4_address: 172.42.120.10

networks:
  ffuf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.120.0/24
