name: httpx-lab

services:
  target:
    build:
      context: .
      dockerfile: target.Dockerfile
    ports:
      - "127.0.0.1:18096:8080"
    networks:
      httpx_net:
        ipv4_address: 172.50.200.20

  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /work
    volumes:
      - ./outputs:/work/outputs
      - ./targets:/work/targets:ro
    depends_on:
      - target
    networks:
      httpx_net:
        ipv4_address: 172.50.200.10

networks:
  httpx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.200.0/24
