name: aircrack-ng-lab

services:
  scanner:
    build:
      context: .
      dockerfile: scanner.Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /work
    volumes:
      - ./outputs:/work/outputs
